name: wings_and_things
description: A productivity app with task management, hydration tracking, and prayer reminders.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #  fl_chart: ^0.61.0 
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  video_player: ^2.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/themes/
    - assets/videos/splash1.mp4
    - assets/videos/splash2.mp4
    - assets/videos/splash3.mp4
    - assets/videos/splash4.mp4


